# -------------------------------------
# Snakefile: set up and module organization
# -------------------------------------
import pandas as pd
import os

# Load sample information and validate
configfile: "config/config.yaml"
samples_df = pd.read_csv(config["sample_info"]["sample_list_path"], sep="\t")

# get current working directory so absolute paths can be used for input/output files
results = os.getcwd()

# load report
report: "report/workflow.rst"

# load resources folder path
resources = config["resources_path"]

# load sample information to be used in workflow
samples = samples_df["sample"]
samples_assemblies_replicates=samples_df["sample"].astype("string") + "_" + samples_df["assembly"].astype("string") + "_" + samples_df["replicate"].astype("string")
samples_assemblies=samples_df["sample"].astype("string") + "_" + samples_df["assembly"].astype("string")

# -------------------------------------
# modularization: rules to include
# -------------------------------------
include: "rules/01_read_preprocessing.smk"


# -------------------------------------
# master rule
# -------------------------------------
rule all:
    input:
        expand(results + "/00_INPUT_DATA/01_reads/{sample_assembly_replicate}_R1.fastq.gz", sample_assembly_replicate=samples_assemblies_replicates),
        expand(results + "/01_READ_PREPROCESSING/04_read_counts/{sample_assembly}_read_counts.csv", sample_assembly=samples_assemblies),
