cluster: mkdir -p slurm_logs/`date +"%y-%m-%d"`/{rule} &&
  sbatch
  --partition={resources.partition}
  --cpus-per-task={threads}
  --mem={resources.mem_mb}
  --job-name=smk-{rule}-{wildcards}
  --output=slurm_logs/`date +"%y-%m-%d"`/{rule}/{rule}-{wildcards}-%j.out
  --account={resources.account}
  --time={resources.runtime}
  --parsable
  --export=ALL
default-resources:
  - partition=compute
  - mem_mb=1000
  - runtime="01:00:00"
  - account=stf
restart-times: 0
max-jobs-per-second: 1
max-status-checks-per-second: 1
latency-wait: 60
jobs: 10
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
conda-prefix: /gscratch/scrubbed/carsonjm/conda_envs
use-singularity: True
singularity-prefix: /gscratch/scrubbed/carsonjm/singularity
singularity-args: "-B /gscratch/ --env APPTAINER_CACHEDIR=/gscratch/scrubbed/carsonjm/.apptainer"
cluster-status: status-sacct.sh
rerun-triggers: mtime
cluster-cancel: scancel
