#------------------------------------
# Sample input information
#------------------------------------
sample_info:
  # path to sample information sheet in TSV format (absolute path)
  sample_list_path: "/home/carsonjm/tool_tests/phide_piper_test/config/samples.tsv"
  # name of the study (for metadata)
  study_name: 'phide_piper_test'
  # information about the ecosystem the sample was obtained from (for metadata)
  sample_ecosystem: "in_silico"


#------------------------------------
# Resources path
#------------------------------------
# path to resources folder (so large databases can be re-used)
resources_path: "/home/carsonjm/tool_tests/resources/"


#------------------------------------
# Rule customization
#------------------------------------
### read_preprocessing ###
# kneaddata arguments
kneaddata:
  # extra kneaddata arguments? (input as a string)
  extra_arguments: "--remove-intermediate-output --verbose --trimmomatic $CONDA_PREFIX/share/trimmomatic-0.39-2"


