---
#------------------------------------
# Pipeline options
#------------------------------------
# path to where samples file is stored
samples_df: "/gscratch/pedslabs/hofflab/carsonjm/CarsonJM/HoffLab_MGX2/config/samples.tsv"
# path to folder where outputs should be stored
results: "/gscratch/pedslabs/hofflab/carsonjm/projects/HoffLab_MGX2_test/"
# path to directory where large downloads should be stored
resources: "/gscratch/scrubbed/carsonjm/resources/"

#------------------------------------
# Database options
#------------------------------------

#------------------------------------
# Rule customization
#------------------------------------
# Module 1: Read Preprocessing
include_read_preprocessing_module: True
read_preprocessing:
  fastp_arguments: "--disable_adapter_trimming --dedup --correction --overrepresentation_analysis"
  fastp_threads: 8
  fastp_runtime: "00:15:00"
  fastp_memory: "10000"
  kneaddata_arguments: ""
  kneaddata_threads: 16
  kneaddata_runtime: "01:00:00"
  kneaddata_memory: "10000"

### Read-based taxonomy ###
include_read_taxonomy_module: True
read_taxonomy:
  metaphlan_arguments: "--unclassified_estimation"
  alpha_diversity: "shannon"
  beta_diversity: "bray-curtis"
  metaphlan_threads: 16
  metaphlan_runtime: "01:00:00"
  metaphlan_memory: "50000"

### Read-based function ###
include_read_function_module: True
read_function:
  humann_arguments: ""
  humann_threads: 16
  humann_runtime: "12:00:00"
  humann_memory: "100000"

### Read-based strain analysis ###
include_read_strain_module: True
read_strain:
  strainphlan_species: ["t__SGB8007_group"]
  strainphlan_arguments: ""
  strainphlan_threads: 16
  strainphlan_runtime: "04:00:00"
  strainphlan_memory: "100000"

### Read-based pangenome analysis ###
include_read_pangenome_module: True
read_pangenome:
  pangenome_species: ["Streptococcus_mitis", "Streptococcus_salivarius"]
  panphlan_map_arguments: ""
  panphlan_profile_arguments: ""
  panphlan_threads: 16
  panphlan_runtime: "01:00:00"
  panphlan_memory: "10000"
