#------------------------------------
# Pipeline options
#------------------------------------
# path to where samples file is stored
samples_df: "/home/carsonjm/CarsonJM/HoffLab_MGX2/config/samples.tsv"
# path to folder where outputs should be stored
results: "/home/carsonjm/results/HoffLab_MGX2_test/"
# path to directory where large downloads should be stored
resources: "/home/carsonjm/resources/"



#------------------------------------
# Database options
#------------------------------------




#------------------------------------
# Rule customization 
#------------------------------------ 
### Preprocessing ###
read_preprocessing:
  clumpify_arguments: "dedupe=t optical=t spany=t adjacent=t"
  kneaddata_arguments: "--remove-intermediate-output --verbose"
  kneaddata_threads: 8


### Read-based taxonomy ###
read_taxonomy:
  metaphlan_arguments: "--unclassified_estimation"
  metaphlan_threads: 8


### Read-based function ###
read_function:
  humann_arguments: ""
  humann_threads: 8


### Read-based phylogeny ###
read_phylogeny:
  samples2markers_arguments: ""
  samples2markers_threads: 4
  strainphlan_arguments: ""
  strainphlan_threads: 8

